### Formatted Print

Printing is handled by a series of macros defined in std::fmt some of which include:

    format!: write formatted text to String
    print!: same as format! but the text is printed to the console (io::stdout).
    println!: same as print! but a newline is appended.
    eprint!: same as format! but the text is printed to the standard error (io::stderr).
    eprintln!: same as eprint!but a newline is appended.

All parse text in the same fashion. As a plus, Rust checks formatting correctness at compile time.

In [52]:
fn formatted_print() {
    // In general, the `{}` will be automatically replaced with any
    // arguments. These will be a stringified
    println!("{} days", 31);   
    
    // Without a suffix, 31 becomes an i32. You can change what type 31 is
    // by providing a suffix.

    // There are various optional patterns this works with. Positional
    // arguments can be used.
    println!("{0}, this is {1}. {1}, this is {0}", "Alice", "Bob");    
    
    // As can named arguments.
    println!("{subject} {verb} {object}",
             object="the lazy dog",
             subject="the quick brown fox",
             verb="jumps over");    
    
    // Special formatting can be specified after a `:`.
    println!("{} of {:b} people know binary, the other half doesn't", 1, 2);    
    
    // You can right-align text with a specified width. This will output
    // "     1". 5 white spaces and a "1".
    println!("{number:>width$}", number=1, width=6);
    
    // You can pad numbers with extra zeroes. This will output "000001".
    println!("{number:>0width$}", number=1, width=6);    
    
    // Rust even checks to make sure the correct number of arguments are
    // used.
    println!("My name is {0}, {1} {0}", "Bond", "James");
    // FIXME ^ Add the missing argument: "James"    
    
    // Create a structure named `Structure` which contains an `i32`.
    #[allow(dead_code)]
    struct Structure(i32);    
    
    // However, custom types such as this structure require more complicated
    // handling. This will not work.
    //println!("This struct `{}` won't print...", Structure(3));
    // FIXME ^ Comment out this line.    
    
    // Add a println! macro that prints: Pi is roughly 3.142 by controlling the number 
    // of decimal places shown. For the purposes of this exercise, use let pi = 3.141592 
    // as an estimate for pi. (Hint: you may need to check the std::fmt documentation for 
    // setting the number of decimals to display)
    let pi = 3.141592;
    
    // Examples followed by pi print
    // Hello {arg 0 ("x")} is {arg 1 (0.01) with precision specified inline (5)}
    // println!("Hello {0} is {1:.5}", "x", 0.01);
    println!("PI = {0:.3}", pi);
    
    // Hello {arg 1 ("x")} is {arg 2 (0.01) with precision specified in arg 0 (5)}
    // println!("Hello {1} is {2:.0$}", 5, "x", 0.01);
    println!("PI = {1:.0$}", 3, pi);
    
    // Hello {arg 0 ("x")} is {arg 2 (0.01) with precision specified in arg 1 (5)}
    // println!("Hello {0} is {2:.1$}", "x", 5, 0.01);
    println!("PI = {0:.1$}", pi, 3);

    // Hello {next arg ("x")} is {second of next two args (0.01) with precision
    //                          specified in first of next two args (5)}
    // println!("Hello {} is {:.*}",    "x", 5, 0.01);
    println!("PI = {:.*}", 3, pi);

    // Hello {next arg ("x")} is {arg 2 (0.01) with precision
    //                          specified in its predecessor (5)}
    // println!("Hello {} is {2:.*}",   "x", 5, 0.01);
    println!("PI = {1:.*}", 3, pi);

    // Hello {next arg ("x")} is {arg "number" (0.01) with precision specified
    //                          in arg "prec" (5)}
    // println!("Hello {} is {number:.prec$}", "x", prec = 5, number = 0.01);
    println!("PI = {number:prec$}", prec = 3, number = pi);
}


formatted_print()

31 days
Alice, this is Bob. Bob, this is Alice
the quick brown fox jumps over the lazy dog
1 of 10 people know binary, the other half doesn't
     1
000001
My name is Bond, James Bond
PI = 3.142
PI = 3.142
PI = 3.142
PI = 3.142
PI = 3.142
PI = 3.141592


()

<p><a href="https://doc.rust-lang.org/std/fmt/"><code>std::fmt</code></a> contains many <a href="../trait.html"><code>traits</code></a> which govern the display
of text. The base form of two important ones are listed below:</p>
<ul>
<li><code>fmt::Debug</code>: Uses the <code>{:?}</code> marker. Format text for debugging purposes.</li>
<li><code>fmt::Display</code>: Uses the <code>{}</code> marker. Format text in a more elegant, user
friendly fashion.</li>
</ul>
<p>Here, we used <code>fmt::Display </code>because the std library provides implementations
for these types. To print text for custom types, more steps are required.</p>
<p>Implementing the <code>fmt::Display</code> trait automatically implements the
<a href="https://doc.rust-lang.org/std/string/trait.ToString.html"><code>ToString</code></a> trait which allows us to <a href="../conversion/string.html">convert</a> the type to <a href="../std/str.html"><code>String</code></a>.</p>
<h3><a class="header" href="#activities" id="activities">Activities</a></h3>
<ul>
<li>Fix the two issues in the above code (see FIXME) so that it runs without
error.</li>
<li>Add a <code>println!</code> macro that prints: <code>Pi is roughly 3.142</code> by controlling
the number of decimal places shown. For the purposes of this exercise,
use <code>let pi = 3.141592</code> as an estimate for pi. (Hint: you may need to
check the <a href="https://doc.rust-lang.org/std/fmt/"><code>std::fmt</code></a> documentation for setting the number of
decimals to display)</li>
</ul>
<h3><a class="header" href="#see-also" id="see-also">See also:</a></h3>
<p><a href="https://doc.rust-lang.org/std/fmt/"><code>std::fmt</code></a>, <a href="../macros.html"><code>macros</code></a>, <a href="../custom_types/structs.html"><code>struct</code></a>,
and <a href="../trait.html"><code>traits</code></a></p>